require(tm)
require(SnowballC)
require(wordcloud)
require(dplyr)
require(e1071)
input <- read.csv(file ="sample.csv", nrows = 10000, header = TRUE, stringsAsFactors = FALSE)
onestar <- filter(input, review_stars == 1)

corp <- Corpus(VectorSource(onestar$review_text))
corp <- tm_map(corp,removePunctuation)
corp <- tm_map(corp, tolower)
corp <- tm_map(corp, removeWords, stopwords('english'))
corp <- tm_map(corp, stripWhitespace)
corp <- tm_map(corp, removeWords, c("the","this","that","with","its","are","their","just","get","will"))
corp <- tm_map(corp,PlainTextDocument)
corp <- tm_map(corp, stemDocument)
wordcloud(corp, max.words = 50, random.order = FALSE)
dtm <- DocumentTermMatrix(corp)
termFreq <- colSums(as.matrix(dtm))
tf <- data.frame(term = names(termFreq), freq = termFreq)
tf <- tf[order(-tf[,2]),]
head(tf)
